FROM kalilinux/kali-rolling

RUN apt update && apt install -y shellinabox
RUN apt instaall -y metasploit-framework
RUN apt clean && rm -rf /var/lib/apt/lists/*
EXPOSE 4200
ENTRYPOINT [ "shellinaboxd" ]
